### PR TITLE
Allow multiple versions per file

### PR DESCRIPTION
**Pull request by blowfishpro**
Had to pull JSON parsing out of AddonInfo ... I think the error paths should be similar but I'm willing to take another look if you don't feel confident in it

### CODE REVIEW

**Comment by blowfishpro** [comment]
@linuxgurugamer got a chance to look at this yet?  I realized I left a couple of WIP messages in the commits but that's fixed now

**Comment by linuxgurugamer** [comment]
Not yet, sorry.  Been very busy with some other stuff.  I'll see if I can make some time this week

**Comment by linuxgurugamer** [comment]
Can you give me an example of the multiple versions in a file, so I can understand this properly and test it?
It's been a while since this was discussedd.
Thanks

**Comment by blowfishpro** [comment]
It would look like an array of version JSON objects
```
[
 {
    "NAME"     : "B9 Part Switch",
    "DOWNLOAD" : "https://github.com/blowfishpro/B9PartSwitch/releases/tag/v2.3.1",
    "URL"      : "https://s3.amazonaws.com/blowfish-ksp-b9partswitch-avc/v2.3.1/B9PartSwitch.version",
    "GITHUB" : {
      "USERNAME"   : "blowfishpro",
      "REPOSITORY" : "B9PartSwitch"
    },
    "VERSION" : "2.3.1",
    "KSP_VERSION" : "1.4.3"
  },
  {
    "NAME"     : "B9 Part Switch",
    "DOWNLOAD" : "https://github.com/blowfishpro/B9PartSwitch/releases/tag/v2.3.2",
    "URL"      : "https://s3.amazonaws.com/blowfish-ksp-b9partswitch-avc/v2.3.2/B9PartSwitch.version",
    "GITHUB" : {
      "USERNAME"   : "blowfishpro",
      "REPOSITORY" : "B9PartSwitch"
    },
    "VERSION" : "2.3.2",
    "KSP_VERSION" : "1.4.4"
  },
  {
    "NAME"     : "B9 Part Switch",
    "DOWNLOAD" : "https://github.com/blowfishpro/B9PartSwitch/releases/tag/v2.3.3",
    "URL"      : "https://s3.amazonaws.com/blowfish-ksp-b9partswitch-avc/v2.3.3/B9PartSwitch.version",
    "GITHUB" : {
      "USERNAME"   : "blowfishpro",
      "REPOSITORY" : "B9PartSwitch"
    },
    "VERSION" : "2.3.3",
    "KSP_VERSION" : "1.4.4"
  }
]
```

**Comment by blowfishpro** [comment]
Still interested in this?  It looks like I'd need to rebase

**Comment by linuxgurugamer** [comment]
On hold right now, going to have to get CKAN to implement this and don't have time right now

**Comment by blowfishpro** [comment]
I wasn't intending for this to require any changes in CKAN.  The idea was that the local .version file distributed with the mod would only ever have one version in it, but the remote .version it grabbed for update checking could have multiple.  As I understand CKAN only looks at the local one.

**Comment by blowfishpro** [comment]
Oh, I see that NetKAN is looking at the remote file if present.  Yeah, that will have to be handled somehow.

**Comment by linuxgurugamer** [comment]
@hebarusan can you take  a look at this and see if it can be added to CKAN?  It's medium priority, I got got a request from @poodmund on the forums about exactly this

**Comment by HebaruSan** [comment]
The usual process for an enhancement is to submit an issue describing it, so it can be investigated, discussed, and developed:
https://github.com/KSP-CKAN/CKAN/issues/new

**Pull request closed without merging**
